package sreenidhi.microfinanceSystem.enumuration;

public enum FileType {
    BORROWER_PHOTO,
    AADHAR,
    PAN,
    BUSINESS_PROOF,
    ADDRESS_PROOF,
    SIGNATURE,
    BANK_STATEMENT,
    SIGNED_CHEQUES,
    GUARANTOR1_AADHAR,
    GUARANTOR1_SIGNATURE,
    GUARANTOR2_AADHAR,
    GUARANTOR2_SIGNATURE
}

